name: build-test


on:
  push:
    tags:
      - "*.*.*"

jobs:
  get-release-url:
    permissions:
      contents: read
    runs-on: 
      group: ubuntu-latest
    outputs:
      release-url: ${{ steps.get-url.outputs.url }}
      latest-tag: ${{ steps.get-url.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: get-url
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest Tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          URL=$(curl -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-Github-Api-Version: 2022-11-28" \ 
          https://api.github.com/zairadotsh/actions-test/$TAG \
          | jq -r '.url')
          echo "Latest Release URL: $URL"
          echo "url=$URL" >> "$GITHUB_OUTPUT"

    
